logging.level.org.springframework: DEBUG
spring:
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: ${logging.path}/root.log
  path: /Users/sroy/git/spring-music/logs
---
spring:
  profiles: mysql
  datasource:
    url: ${vcap.services.mysql.credentials.jdbcUrl}
    username: ${vcap.services.mysql.credentials.username}
    password: ${vcap.services.mysql.credentials.password}
---
spring:
  profiles: cloudfoundry
  data:
    mongodb:
      url: ${vcap.services.swagata-mongo-db.credentials.uri}

---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect

